// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	time "time"

	tkonephioorgv1alpha1 "github.com/nephio-experimental/tko/api/krm/tko.nephio.org/v1alpha1"
	versioned "github.com/nephio-experimental/tko/api/kubernetes-client/clientset/versioned"
	internalinterfaces "github.com/nephio-experimental/tko/api/kubernetes-client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/nephio-experimental/tko/api/kubernetes-client/listers/tko.nephio.org/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// SiteInformer provides access to a shared informer and lister for
// Sites.
type SiteInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.SiteLister
}

type siteInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// NewSiteInformer constructs a new informer for Site type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewSiteInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredSiteInformer(client, resyncPeriod, indexers, nil)
}

// NewFilteredSiteInformer constructs a new informer for Site type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredSiteInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.TkoV1alpha1().Sites().List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.TkoV1alpha1().Sites().Watch(context.TODO(), options)
			},
		},
		&tkonephioorgv1alpha1.Site{},
		resyncPeriod,
		indexers,
	)
}

func (f *siteInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredSiteInformer(client, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *siteInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&tkonephioorgv1alpha1.Site{}, f.defaultInformer)
}

func (f *siteInformer) Lister() v1alpha1.SiteLister {
	return v1alpha1.NewSiteLister(f.Informer().GetIndexer())
}
