apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tko

resources:
- admin/namespace.yaml
- admin/rbac.yaml
- admin/api.yaml
- workloads/tko-data.yaml
- workloads/tko-preparer.yaml
- workloads/tko-meta-scheduler.yaml
- workloads/tko-runner.yaml
- workloads/postgresql.yaml

images:
# See: https://hub.docker.com/u/tliron
- name: tko-data
  newName: docker.io/tliron/tko-data
  newTag: latest
- name: tko-preparer
  newName: docker.io/tliron/tko-preparer
  newTag: latest
- name: tko-meta-scheduler
  newName: docker.io/tliron/tko-meta-scheduler
  newTag: latest
- name: tko-runner
  newName: docker.io/tliron/tko-runner
  newTag: latest

# See: https://hub.docker.com/_/postgres
- name: postgresql
  newName: docker.io/postgres
  newTag: 17rc1-alpine

# See: https://hub.docker.com/_/docker
- name: docker-dind
  newName: docker.io/docker
  newTag: 27.3.1-dind
