// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/nephio-experimental/tko/api/krm/tko.nephio.org/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeTemplates implements TemplateInterface
type FakeTemplates struct {
	Fake *FakeTkoV1alpha1
}

var templatesResource = v1alpha1.SchemeGroupVersion.WithResource("templates")

var templatesKind = v1alpha1.SchemeGroupVersion.WithKind("Template")

// Get takes name of the template, and returns the corresponding template object, and an error if there is any.
func (c *FakeTemplates) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.Template, err error) {
	emptyResult := &v1alpha1.Template{}
	obj, err := c.Fake.
		Invokes(testing.NewRootGetActionWithOptions(templatesResource, name, options), emptyResult)
	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha1.Template), err
}

// List takes label and field selectors, and returns the list of Templates that match those selectors.
func (c *FakeTemplates) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.TemplateList, err error) {
	emptyResult := &v1alpha1.TemplateList{}
	obj, err := c.Fake.
		Invokes(testing.NewRootListActionWithOptions(templatesResource, templatesKind, opts), emptyResult)
	if obj == nil {
		return emptyResult, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.TemplateList{ListMeta: obj.(*v1alpha1.TemplateList).ListMeta}
	for _, item := range obj.(*v1alpha1.TemplateList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested templates.
func (c *FakeTemplates) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchActionWithOptions(templatesResource, opts))
}

// Create takes the representation of a template and creates it.  Returns the server's representation of the template, and an error, if there is any.
func (c *FakeTemplates) Create(ctx context.Context, template *v1alpha1.Template, opts v1.CreateOptions) (result *v1alpha1.Template, err error) {
	emptyResult := &v1alpha1.Template{}
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateActionWithOptions(templatesResource, template, opts), emptyResult)
	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha1.Template), err
}

// Update takes the representation of a template and updates it. Returns the server's representation of the template, and an error, if there is any.
func (c *FakeTemplates) Update(ctx context.Context, template *v1alpha1.Template, opts v1.UpdateOptions) (result *v1alpha1.Template, err error) {
	emptyResult := &v1alpha1.Template{}
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateActionWithOptions(templatesResource, template, opts), emptyResult)
	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha1.Template), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeTemplates) UpdateStatus(ctx context.Context, template *v1alpha1.Template, opts v1.UpdateOptions) (result *v1alpha1.Template, err error) {
	emptyResult := &v1alpha1.Template{}
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceActionWithOptions(templatesResource, "status", template, opts), emptyResult)
	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha1.Template), err
}

// Delete takes name of the template and deletes it. Returns an error if one occurs.
func (c *FakeTemplates) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteActionWithOptions(templatesResource, name, opts), &v1alpha1.Template{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeTemplates) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionActionWithOptions(templatesResource, opts, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.TemplateList{})
	return err
}

// Patch applies the patch and returns the patched template.
func (c *FakeTemplates) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.Template, err error) {
	emptyResult := &v1alpha1.Template{}
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceActionWithOptions(templatesResource, name, pt, data, opts, subresources...), emptyResult)
	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha1.Template), err
}
