// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/nephio-experimental/tko/api/kubernetes-client/clientset/versioned/typed/tko.nephio.org/v1alpha1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeTkoV1alpha1 struct {
	*testing.Fake
}

func (c *FakeTkoV1alpha1) Deployments(namespace string) v1alpha1.DeploymentInterface {
	return &FakeDeployments{c, namespace}
}

func (c *FakeTkoV1alpha1) Plugins(namespace string) v1alpha1.PluginInterface {
	return &FakePlugins{c, namespace}
}

func (c *FakeTkoV1alpha1) Sites() v1alpha1.SiteInterface {
	return &FakeSites{c}
}

func (c *FakeTkoV1alpha1) Templates() v1alpha1.TemplateInterface {
	return &FakeTemplates{c}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeTkoV1alpha1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
