- name: Prepare DU
  hosts: all
  connection: local
  gather_facts: false

  collections:
  - tko.tko

  module_defaults:
    group/tko.tko.tko:
      host: "{{ TKO_DATA_HOST }}"

  tasks:

  - name: Test TKO
    register: deployments
    tko_deployments:
      site_id: "{{ inventory_hostname }}"

  # TODO: prepare deployments

  - name: Log deployments
    debug: var=deployments.deployments
