- name: Prepare DU
  hosts: localhost
  gather_facts: false

  collections:
  - tko.tko

  module_defaults:
    group/tko.tko.tko:
      host: "{{ TKO_DATA_HOST }}"

  tasks:

  - name: Test TKO
    register: result
    tko_deployments: {}

  - name: Dump deployments
    debug: var=result.deployments
