- name: Prepare DU
  hosts: all
  connection: local
  gather_facts: false

  collections:
  - tko.tko

  module_defaults:
    group/tko.tko.tko:
      host: "{{ TKO_DATA_HOST }}"

  tasks:

  - name: Get deployments for site
    tko_list_deployments:
      site_id: "{{ inventory_hostname }}"
    register: deployments

  - name: Modify deployment
    loop: "{{ deployments.deployments }}"
    # To loop over several tasks we must put them in a separate file
    include_tasks: tasks/modify-deployment.yaml
