- name: Provision Cluster
  hosts: all
  connection: local
  gather_facts: false

  collections:
  - kubernetes.core

  roles:
  # Creates /tmp/ca.crt from K8S_AUTH_SSL_CA_CERT_CONTENT
  - k8s_ca_cert

  module_defaults:
    group/k8s:
      host: "{{ K8S_AUTH_HOST }}"
      api_key: "{{ K8S_AUTH_API_KEY }}"
      ca_cert: /tmp/ca.crt

  tasks:

  - name: Find cluster resource
    loop: "{{ package }}"
    when: (item.apiVersion == "ansible.plugin.nephio.org/v1alpha1") and (item.kind == "Cluster")
    debug: var=item
    register: cluster_resource

  - name: Log cluster name
    debug: var=cluster_resource.results[0].item.metadata.name

  - name: Get existing clusters
    k8s_exec:
      namespace: tko
      pod: tko-runner
      container: tko-runner
      command: kind get clusters
    register: existing_clusters

  - name: Log existing clusters
    debug: var=existing_clusters.stdout_lines

  # TODO: copy cluster_resource.results[0].item to file at tko-runner

  - name: Create cluster
    when: existing_clusters.stdout_lines is not contains(cluster_resource.results[0].item.metadata.name)
    # TODO: we'll want to k8s_exec "kind create"
    debug:
      msg: "kind create {{ cluster_resource.results[0].item.metadata.name }}"
