- name: Provision Cluster
  hosts: all
  connection: local
  gather_facts: false

  collections:
  - kubernetes.core

  roles:
  # Creates /tmp/ca.crt from K8S_AUTH_SSL_CA_CERT_CONTENT
  - k8s_ca_cert

  module_defaults:
    group/k8s:
      host: "{{ K8S_AUTH_HOST }}"
      api_key: "{{ K8S_AUTH_API_KEY }}"
      ca_cert: /tmp/ca.crt

  tasks:

  # TODO: copy resource to file, "kind create cluster"

  - name: Get existing clusters
    register: existing_clusters
    k8s_exec:
      namespace: tko
      pod: tko-runner
      container: tko-runner
      command: kind get clusters

  - name: Log existing clusters
    debug: var=existing_clusters.stdout_lines
