- name: Testing K8s
  hosts: all
  gather_facts: false
  
  collections:
  - kubernetes.core
  - ansible.netcommon

  - name: Get the pods in the tko namespace
    k8s_info:
      api_version: v1
      kind: Pod
      namespace: tko
      #kubeconfig: ./kubeconfig
      host: https://kubernetes.default.svc
      ca_cert: ./serviceaccount/ca.crt
      api_key: ./serviceaccount/token
    register: pod_list

  - name: Print pod names
    debug:
      msg: "pod_list: {{ pod_list | json_query('resources[*].metadata.name') }}"
