apiVersion: ansible.plugin.nephio.org/v1alpha1
kind: Cluster

# Will be converted by the plugin to:
# apiVersion: kind.x-k8s.io/v1alpha4
# kind: Cluster

metadata:
  name: dublin-north

name: dublin-north
networking:
  apiServerAddress: 127.0.0.1
  apiServerPort: 31001
  podSubnet: 10.99.0.0/16
  serviceSubnet: 10.199.0.0/16
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 30000
    hostPort: 32003
