# This will create a token that we will use for our playbooks to access the local Kubernetes API
#
# https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#manually-create-a-long-lived-api-token-for-a-serviceaccount

apiVersion: v1
kind: Secret

metadata:
  name: awx-tko
  namespace: tko
  annotations:
    kubernetes.io/service-account.name: awx

type: kubernetes.io/service-account-token
