// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

type DeploymentExpansion interface{}

type PluginExpansion interface{}

type SiteExpansion interface{}

type TemplateExpansion interface{}
