// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"

	v1alpha1 "github.com/nephio-experimental/tko/api/krm/tko.nephio.org/v1alpha1"
	scheme "github.com/nephio-experimental/tko/api/kubernetes-client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// SitesGetter has a method to return a SiteInterface.
// A group's client should implement this interface.
type SitesGetter interface {
	Sites() SiteInterface
}

// SiteInterface has methods to work with Site resources.
type SiteInterface interface {
	Create(ctx context.Context, site *v1alpha1.Site, opts v1.CreateOptions) (*v1alpha1.Site, error)
	Update(ctx context.Context, site *v1alpha1.Site, opts v1.UpdateOptions) (*v1alpha1.Site, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, site *v1alpha1.Site, opts v1.UpdateOptions) (*v1alpha1.Site, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.Site, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.SiteList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.Site, err error)
	SiteExpansion
}

// sites implements SiteInterface
type sites struct {
	*gentype.ClientWithList[*v1alpha1.Site, *v1alpha1.SiteList]
}

// newSites returns a Sites
func newSites(c *TkoV1alpha1Client) *sites {
	return &sites{
		gentype.NewClientWithList[*v1alpha1.Site, *v1alpha1.SiteList](
			"sites",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *v1alpha1.Site { return &v1alpha1.Site{} },
			func() *v1alpha1.SiteList { return &v1alpha1.SiteList{} }),
	}
}
