- name: Start deployment modification
  tko_start_deployment_modification:
    deployment_id: "{{ item.deployment_id }}"
  register: modification

- name: Set deployment package label
  set_label:
    package: "{{ modification.package }}"
    label: network_service
    value: du
  register: modified

- name: Log modified deployment package
  debug:
    msg: "{{ modified.package }}"

- name: End deployment modification
  tko_end_deployment_modification:
    modification_token: "{{ modification.modification_token }}"
    package: "{{ modified.package }}"
