#!/bin/bash
set -e

HERE=$(dirname "$(readlink --canonicalize "$BASH_SOURCE")")
. "$HERE/_env"
. "$HERE/_trap"

not_root

"$HERE/build"

mkdir --parents "$ROOT/work/"

build () {
	local NAME=$1
	if [ -f "$GOPATH/bin/$NAME" ]; then
		cp --force "$GOPATH/bin/$NAME" "$ROOT/work/"
	fi
	docker build --tag="$NAME" --file="assets/docker/$NAME" --build-arg="ALPINE_VERSION=$ALPINE_VERSION" "$ROOT"
}

build tko-api
if [ "$1" != -a ]; then
	build tko-preparer
	build tko-meta-scheduler
	build tko-runner # doesn't have an executable
fi
