#!/bin/bash
set -e

HERE=$(dirname "$(readlink --canonicalize "$BASH_SOURCE")")
. "$HERE/_env"
. "$HERE/_trap"

not_root

"$HERE/build"

mkdir --parents "$ROOT/work/"

build () {
	if [ -f "$GOPATH/bin/$1" ]; then
		cp --force "$GOPATH/bin/$1" "$ROOT/work/"
	fi
	docker build --tag="$1" --file="assets/docker/$1" "$ROOT"
}

build tko-api
if [ "$1" != -a ]; then
	build tko-preparer
	build tko-meta-scheduler
	build tko-runner
fi
