#!/bin/bash
set -e

HERE=$(dirname "$(readlink --canonicalize "$BASH_SOURCE")")
. "$HERE/_env"
. "$HERE/_trap"

not_root

NAME=tko-ansible-execution-environment
TAG=${TAG:-$DOCKER_REGISTRY}

cat "$ROOT/assets/ansible/_execution-environment.yaml" |
ALPINE_VERSION=$ALPINE_VERSION ANSIBLE_CORE_VERSION=$ANSIBLE_CORE_VERSION ANSIBLE_RUNNER_VERSION=$ANSIBLE_RUNNER_VERSION \
envsubst > "$ROOT/assets/ansible/execution-environment.yaml"

rm --recursive --force "$ROOT/work/ansible-builder/"

"$PYTHON_ENV/bin/ansible-builder" build \
	--file="$ROOT/assets/ansible/execution-environment.yaml" \
	--context="$ROOT/work/ansible-builder" \
	--container-runtime=docker \
	--tag="$NAME"

docker image tag "$NAME" "$TAG/$NAME"
docker push "$TAG/$NAME"
