#!/bin/bash
set -e

HERE=$(dirname "$(readlink --canonicalize "$BASH_SOURCE")")
. "$HERE/_env"
. "$HERE/_trap"

not_root

ORG=github.com/nephio-experimental
REPO=$ORG/tko
API_PKG=$REPO/api

BOILERPLATE=$ROOT/assets/kubernetes/kube_codegen/boilerplate.go.txt
OPENAPI_REPORT=$ROOT/assets/kubernetes/kube_codegen/gen_openapi.report

go get "k8s.io/code-generator@v$KUBERNETES_VERSION"
CODE_GENERATOR=$(go list -f '{{.Dir}}' -m "k8s.io/code-generator@v$KUBERNETES_VERSION")
. "${CODE_GENERATOR}/kube_codegen.sh"

m 'gen_helpers...'

kube::codegen::gen_helpers \
	--boilerplate "$BOILERPLATE" \
	"$ROOT/api/krm"

m 'gen_openapi...'

rm --recursive --force "$ROOT/api/openapi"

# Note: lots of validation errors from Kubernetes meta package; can be ignored
kube::codegen::gen_openapi \
	--output-dir "$ROOT/api/openapi" \
	--output-pkg "$API_PKG/openapi" \
	--boilerplate "$BOILERPLATE" \
	--report-filename "$OPENAPI_REPORT" \
	--update-report \
	"$ROOT/api/krm"

m 'gen_client...'

rm --recursive --force "$ROOT/api/kubernetes-client"

# To avoid warnings
mkdir --parents "$ROOT/api/kubernetes-client/clientset/"
mkdir --parents "$ROOT/api/kubernetes-client/listers/"
mkdir --parents "$ROOT/api/kubernetes-client/informers/"

kube::codegen::gen_client \
	--output-dir "$ROOT/api/kubernetes-client" \
	--output-pkg "$API_PKG/kubernetes-client" \
	--boilerplate "$BOILERPLATE" \
	--with-watch \
	"$ROOT/api/krm"

# Our "go get" added dependencies that we don't need
cd "$ROOT"
go mod tidy
