#!/bin/bash
set -e

HERE=$(dirname "$(readlink --canonicalize "$BASH_SOURCE")")
. "$HERE/_env"

not_root

export BACKEND=${BACKEND:-memory}
export GRPC_IP_STACK=${GRPC_IP_STACK:-dual}

function install_service () {
    local NAME=$1
    cat "$ROOT/assets/systemd/$NAME.service" | envsubst > ~/".config/systemd/user/$NAME.service"
}

mkdir --parents ~/.config/systemd/user/

install_service tko-api-server
install_service tko-meta-scheduler
install_service tko-preparer

systemctl --user daemon-reload
