#!/bin/bash
set -e

HERE=$(dirname "$(readlink --canonicalize "$BASH_SOURCE")")
. "$HERE/_env"

not_root

if [ "$1" == -c ]; then
	rm --force --recursive "$PYTHON_ENV"
fi

python3 -m venv "$PYTHON_ENV"

. "$PYTHON_ENV/bin/activate"
pip install --upgrade pip
pip install ruamel.yaml cbor2 grpcio-tools ansible ansible-builder awxkit

# "grpcio-tools" is just for building
# "awxkit" is for the awx CLI tools
# "ansible" is so that we can use ansible-playbook and ansible-galaxy commands
