#!/bin/bash
set -e

HERE=$(dirname "$(readlink --canonicalize "$BASH_SOURCE")")
. "$HERE/_env"

not_root

NAME=${NAME:-Local}
BACKEND=${BACKEND:-memory}
BACKEND_CLEAN=${BACKEND_CLEAN:-false}
GRPC_IP_STACK=${GRPC_IP_STACK:-dual}

mkdir --parents ~/.config/systemd/user/

function install_service () {
    local SERVICE=$1
    cat "$ROOT/assets/systemd/$SERVICE.service" | NAME=$NAME BACKEND=$BACKEND BACKEND_CLEAN=$BACKEND_CLEAN GRPC_IP_STACK=$GRPC_IP_STACK envsubst > ~/".config/systemd/user/$SERVICE.service"
}

install_service tko-api
install_service tko-meta-scheduler
install_service tko-preparer

systemctl --user daemon-reload
