#!/bin/bash
set -e

HERE=$(dirname "$(readlink --canonicalize "$BASH_SOURCE")")
. "$HERE/_env"
. "$HERE/_trap"

only_root

DNF_ARGS=
if [ "$1" == -y ]; then
	DNF_ARGS=--assumeyes
fi

dnf install \
bash-completion kitty-terminfo zip jq \
golang protobuf-compiler \
python3-virtualenv \
postgresql-server postgresql-contrib $DNF_ARGS

# Note: if Fedora's version of golang is not recent enough, use scripts/install-go

systemctl enable postgresql
postgresql-setup --initdb --unit postgresql || true

# Enable md5 authentication for PostgreSQL

sed --in-place --expression \
"s|host    replication     all             127.0.0.1/32            ident|host    replication     all             127.0.0.1/32            md5|" \
/var/lib/pgsql/data/pg_hba.conf

sed --in-place --expression \
"s|host    all             all             ::1/128                 ident|host    all             all             ::1/128                 md5|" \
/var/lib/pgsql/data/pg_hba.conf

systemctl restart postgresql

# https://developer.fedoraproject.org/tools/docker/docker-installation.html

dnf remove podman-docker $DNF_ARGS
dnf config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo $DNF_ARGS
dnf install docker-ce docker-ce-cli containerd.io $DNF_ARGS

systemctl enable --now docker

# gpasswd will add the group to the current session, unlike usermod
# (unfortunately this does not affect the user's systemd daemon)
gpasswd --add "$SUDO_USER" docker
