#!/bin/bash
set -e

HERE=$(dirname "$(readlink --canonicalize "$BASH_SOURCE")")
. "$HERE/_env"

only_root

dnf install \
protobuf-compiler \
python3-virtualenv \
postgresql-server postgresql-contrib

# See: https://docs.fedoraproject.org/en-US/quick-docs/postgresql/

systemctl enable postgresql
postgresql-setup --initdb --unit postgresql || true
systemctl restart postgresql

# https://developer.fedoraproject.org/tools/docker/docker-installation.html

dnf remove podman-docker
dnf config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo
dnf install docker-ce docker-ce-cli containerd.io

systemctl enable --now docker

groupadd docker || true
usermod --append --groups docker "$SUDO_USER"
