#!/bin/bash
set -e

HERE=$(dirname "$(readlink --canonicalize "$BASH_SOURCE")")
. "$HERE/_env"

not_root

# See: https://github.com/scop/bash-completion/blob/master/README.md

USER_DIR=$BASH_COMPLETION_USER_DIR

if [ -z "$USER_DIR" ]; then
	DATA_HOME=$XDG_DATA_HOME
	if [ -z "$DATA_HOME" ]; then
		DATA_HOME=$HOME/.local/share
	fi 
	USER_DIR=$DATA_HOME/bash-completion
fi

function c () {
	local NAME=$1
	"$NAME" completion bash > "$USER_DIR/completions/$NAME"
}

mkdir --parents "$USER_DIR/completions"

c tko
c tko-api
c tko-preparer
c tko-meta-scheduler

c kind
c kubectl
c helm
c kpt

if [ "$1" == -r ]; then
	reset
fi
