#!/bin/bash
set -e

HERE=$(dirname "$(readlink --canonicalize "$BASH_SOURCE")")
. "$HERE/_env"

not_root

# See: https://github.com/ansible-community/awx-operator-helm

helm repo add awx-operator https://ansible-community.github.io/awx-operator-helm/

if [ "$1" == -c ]; then
	kubectl delete --filename="$ROOT/assets/kubernetes/workloads/awx.yaml" || true
	helm uninstall awx-operator --kube-context=kind-tko --namespace=tko || true
fi

helm install awx-operator awx-operator/awx-operator --version=1.3.0 --kube-context=kind-tko --namespace=tko || true

kubectl apply --filename="$ROOT/assets/kubernetes/workloads/awx.yaml"

m 'It may take ~5 minutes for the PostgreSQL database to be ready before AWX is up'

#kubectl logs deployment/awx -c awx-web -n tko -f