#!/bin/bash
set -e

HERE=$(dirname "$(readlink --canonicalize "$BASH_SOURCE")")
. "$HERE/_env"

only_root

DNF_ARGS=
if [ "$1" == -y ]; then
	DNF_ARGS=--assumeyes
fi

dnf install \
wget zip \
golang protobuf-compiler \
python3-virtualenv \
postgresql-server postgresql-contrib $DNF_ARGS

# See: https://docs.fedoraproject.org/en-US/quick-docs/postgresql/

systemctl enable postgresql
postgresql-setup --initdb --unit postgresql || true
systemctl restart postgresql

# https://developer.fedoraproject.org/tools/docker/docker-installation.html

dnf remove podman-docker $DNF_ARGS
dnf config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo $DNF_ARGS
dnf install docker-ce docker-ce-cli containerd.io $DNF_ARGS

systemctl enable --now docker

groupadd docker || true
usermod --append --groups docker "$SUDO_USER"
