#!/bin/bash
set -e

# This script is intended to be run inside the Vagrant virtual machine

HERE=/vagrant/scripts
. "$HERE/_env"
. "$HERE/_trap"

not_root

m 'increasing inotify limits...' $CYAN
# See: https://kind.sigs.k8s.io/docs/user/known-issues/#pod-errors-due-to-too-many-open-files
echo 'fs.inotify.max_user_watches = 524288' | sudo tee --append /etc/sysctl.conf
echo 'fs.inotify.max_user_instances = 512' | sudo tee --append /etc/sysctl.conf

m 'install-system-dependencies-fedora...' $CYAN
sudo "$HERE/install-system-dependencies-fedora" -y

m 'install-system-dependencies...' $CYAN
sudo "$HERE/install-system-dependencies"

m 'setup-postgresql...' $CYAN
sudo "$HERE/setup-postgresql"

m 'install-python-env...' $CYAN
"$HERE/install-python-env"

m 'install-systemd-services...' $CYAN
NAME=Vagrant BACKEND=postgresql BACKEND_CLEAN=true "$HERE/install-systemd-services"

m 'install-go...' $CYAN
"$HERE/install-go"

m 'build...' $CYAN
export PATH=$HOME/.go/bin:$PATH
"$HERE/build"

m 'install-bash-completion...' $CYAN
export PATH=$HOME/go/bin:$PATH
"$HERE/install-bash-completion"
