#!/bin/bash
set -e

HERE=$(dirname "$(readlink --canonicalize "$BASH_SOURCE")")
. "$HERE/_env"

not_root

"$HERE/kubectl-kind" exec --context=kind-tko --namespace=tko --container=tko-runner --stdin --tty pod/tko-runner -- "$@"
