#!/bin/bash
set -e

HERE=$(dirname "$(readlink --canonicalize "$BASH_SOURCE")")
. "$HERE/_env"

not_root

NAME=$1

# See: https://man7.org/linux/man-pages/man1/journalctl.1.html#OUTPUT_OPTIONS
OUTPUT=${OUTPUT:-cat}

journalctl --user-unit="$NAME.service" --output="$OUTPUT" "${@:2}"
