#!/bin/bash
set -e

HERE=$(dirname "$(readlink --canonicalize "$BASH_SOURCE")")
. "$HERE/_env"
. "$HERE/_trap"

not_root

TAG=${TAG:-tliron}

function push () {
	docker image tag "$1" "$TAG/$1"
	docker push "$TAG/$1"
}

push tko-api
if [ "$1" != -a ]; then
	push tko-preparer
	push tko-meta-scheduler
	push tko-runner
fi
