#!/bin/bash
set -e

HERE=$(dirname "$(readlink --canonicalize "$BASH_SOURCE")")
. "$HERE/_env"
. "$HERE/_trap"

not_root

function push () {
	local NAME=$1
	docker image tag "$NAME" "$DOCKER_REPOSITORY/$DOCKER_REGISTRY/$NAME"
	docker push "$DOCKER_REPOSITORY/$DOCKER_REGISTRY/$NAME"
}

push tko-data
if [ "$1" != -a ]; then
	push tko-preparer
	push tko-meta-scheduler
	push tko-runner
fi
