#!/bin/bash
set -e

HERE=$(dirname "$(readlink --canonicalize "$BASH_SOURCE")")
. "$HERE/_env"
. "$HERE/_trap"

function push () {
	docker image tag "$1" "tliron/$1"
	docker push "tliron/$1"
}

push tko-api
push tko-preparer
push tko-meta-scheduler
