#!/bin/bash
set -e

HERE=$(dirname "$(readlink --canonicalize "$BASH_SOURCE")")
. "$HERE/_env"

not_root

"$HERE/start-service" tko-api
"$HERE/start-service" tko-preparer
"$HERE/start-service" tko-meta-scheduler
