#!/bin/bash
set -e

HERE=$(dirname "$(readlink --canonicalize "$BASH_SOURCE")")
. "$HERE/_env"
. "$HERE/_trap"

not_root

m 'stopping controllers...'

"$HERE/stop-services"

m 'deleting workload clusters...'

kind delete cluster --name=edge1 || true
kind delete cluster --name=edge2 || true

m 'building...'

"$HERE/build"

m 'starting controllers...'

"$HERE/start-services"

set +e
while true; do
	waiting 'waiting for tko-data...'
	if tko about --quiet; then
		break
	fi
	sleep 0.5
done
set -e
end_waiting 'tko-data is up'

"$HERE/test-scenario" local

m 'templates:'

tko template list

m 'sites:'

tko site list

m 'plugins:'

tko plugin list

m 'deployments:'

tko deployment list
