#!/bin/bash
set -e

HERE=$(dirname "$(readlink --canonicalize "$BASH_SOURCE")")
. "$HERE/_env"
. "$HERE/_trap"

not_root

if [ "$1" == -c ]; then
	m 'deleting cluster...'
	kind delete cluster --name=tko || true

	m 'deleting volumes (via sudo)...'
	# If we don't do this, Docker-in-Docker (and thus Kind) will get confused with existing data
	sudo rm --recursive --force /tmp/tko-postgresql /tmp/tko-docker
fi

# if [ ! -d /var/local-path-provisioner ]; then
# 	m 'setting up Kind local path provisioner for "standard" storage class (via sudo)...'
# 	sudo mkdir --parents /var/local-path-provisioner
# 	sudo chown "$SUDO_USER" /var/local-path-provisioner
# fi

m 'creating cluster...'

kind create cluster --config="$ROOT/assets/kubernetes/kind/tko.yaml" || true

if [ "$1" == -d ]; then
	m 'deleting TKO...'
	"$HERE/kubectl-kind" delete --kustomize="$ROOT/assets/kubernetes/" || true
	kubectl wait --for=delete namespace/tko

	m 'deleting volumes (via sudo)...'
	# If we don't do this, Docker-in-Docker (and thus Kind) will get confused with existing data
	sudo rm --recursive --force /tmp/tko-postgresql /tmp/tko-docker
fi

m 'deploying TKO...'

"$HERE/kubectl-kind" apply --kustomize="$ROOT/assets/kubernetes/"

m 'waiting for TKO...'

TIMEOUT=180s
"$HERE/kubectl-kind" wait deployment/postgresql --namespace=tko --for=condition=available --timeout="$TIMEOUT"
"$HERE/kubectl-kind" wait deployment/tko-api --namespace=tko --for=condition=available --timeout="$TIMEOUT"
"$HERE/kubectl-kind" wait pod/tko-runner --namespace=tko --for=condition=ready --timeout="$TIMEOUT"
"$HERE/kubectl-kind" wait apiservice/v1alpha1.tko.nephio.org --for=condition=available --timeout="$TIMEOUT"

m 'creating KRM...'

"$HERE/kubectl-kind" apply --filename="$ROOT/examples/kubernetes/templates.yaml"
"$HERE/kubectl-kind" apply --filename="$ROOT/examples/kubernetes/sites.yaml"
"$HERE/kubectl-kind" create --filename="$ROOT/examples/kubernetes/deployments.yaml"

"$HERE/test-scenario" remote "$HERE/tko-kind"
