#!/bin/bash
set -e

HERE=$(dirname "$(readlink --canonicalize "$BASH_SOURCE")")
. "$HERE/_env"

m 'stopping controllers...'

"$HERE/stop-service" tko-meta-scheduler
"$HERE/stop-service" tko-preparer
"$HERE/stop-service" tko-api

if [ "$1" == -c ]; then
	m 'deleting clusters...'
    kind delete cluster --name edge1 || true
    kind delete cluster --name edge2 || true
fi

m 'building...'

"$HERE/build"

m 'starting controllers...'

"$HERE/start-service" tko-api
"$HERE/start-service" tko-preparer
"$HERE/start-service" tko-meta-scheduler

set +e
while true; do
	m 'waiting for tko-api...'
	if tko template list --quiet; then
		break
	fi
	sleep 1
done
set -e

m 'registering plugins...'

tko plugin register validate free5gc/smf "$ROOT/examples/plugins/validate_free5gc_smf.py" --trigger=free5gc.plugin.nephio.org,v1alpha1,SMF -v
tko plugin register prepare namespace --executor=kpt gcr.io/kpt-fn/set-namespace:v0.4.1 --property=namespace=spec.namespace --trigger=workload.plugin.nephio.org,v1alpha1,Namespace -v
tko plugin register prepare free5gc/smf "$ROOT/examples/plugins/prepare_free5gc_smf.py" --trigger=free5gc.plugin.nephio.org,v1alpha1,SMF -v
tko plugin register schedule kind "$ROOT/examples/plugins/schedule_kind.py" --trigger=kind.x-k8s.io,v1alpha4,Cluster -v
tko plugin register schedule gdce "$ROOT/examples/plugins/schedule_gdce.py" --trigger=gdce.google.com,v1alpha1,EdgeCluster -v

m 'registering templates...'

tko template register demo/hello-world:v1.0.0 --metadata=type=demo --url="$ROOT/examples/hello-world/" -v
tko template register nf/free5gc/upf:v1.0.0 --metadata=type=nf --url="$ROOT/examples/free5gc-upf/" -v
tko template register nf/free5gc/smf:v1.0.0 --metadata=type=nf --url="$ROOT/examples/free5gc-smf/" -v
tko template register topology/oran/cu:v1.0.0 --metadata=type=topology --url="$ROOT/examples/oran-cu/" -v
tko template register topology/oran/du:v1.0.0 --metadata=type=topology --url="$ROOT/examples/oran-du/krm/" -v
tko template register site/gdce:v1.0.0 --metadata=type=site --url="$ROOT/examples/gdce-site/" -v

# From zip file
#pushd "$ROOT/examples/free5gc-smf/" > /dev/null
#rm --force /tmp/tko-free5gc-smf.zip
#zip --recurse-paths /tmp/tko-free5gc-smf.zip .
#popd > /dev/null
#tko template register free5gc/smf2 --url=/tmp/tko-free5gc-smf.zip

# From zip URL
#tko template register free5gc/smf2 --url='zip:https://github.com/nephio-experimental/tko/archive/refs/heads/main.zip!tko-main/examples/free5gc-smf/infra.yaml'

# From git URL
#tko template register free5gc/smf2 -url='git:https://github.com/nephio-experimental/tko.git!examples/free5gc-smf/infra.yaml'

m 'registering sites...'

tko site register lab/1 --metadata=type=lab --url="$ROOT/examples/lab-site/" -v
tko site register india/bangalore/south-100 site/gdce:v1.0.0 --metadata=Site.cloud=GDC-E --metadata=Site.region=bangalore -v
tko site register india/bangalore/south-101 site/gdce:v1.0.0 --metadata=Site.cloud=GDC-E --metadata=Site.region=bangalore -v
tko site register usa/chicago/west-4 site/gdce:v1.0.0 --metadata=Site.cloud=GDC-E --metadata=Site.region=chicago -v
tko site register usa/chicago/west-5 site/gdce:v1.0.0 --metadata=Site.cloud=GDC-E --metadata=Site.region=chicago -v

m 'creating CSAR...'

pushd "$ROOT/examples/oran-du/csar/" > /dev/null
rm --force /tmp/tko-oran-du.csar
zip --recurse-paths /tmp/tko-oran-du.csar .
popd > /dev/null

m 'creating deployments...'

tko deployment create demo/hello-world:v1.0.0 --site=lab/1 -v
tko deployment create topology/oran/cu:v1.0.0 -v
tko deployment create topology/oran/du:v1.0.0 -v

# D=$(tko deployment create topology/oran/cu:v1.0.0 -v)
# m "deployment name: $D"
# tko deployment get "$D"
# M=$(tko deployment mod start "$D" --url="$ROOT/work/deployment/")
# m "modification token: $M"
# kpt fn eval --image=gcr.io/kpt-fn/set-namespace:v0.4.1 "$ROOT/work/deployment/" -- namespace=network-function
# tko deployment mod end "$M" --url="$ROOT/work/deployment/"
# TODO: set prepared?

m 'templates:'

tko template list

m 'sites:'

tko site list

m 'plugins:'

tko plugin list

m 'deployments:'

tko deployment list
