#!/bin/bash
set -e

HERE=$(dirname "$(readlink --canonicalize "$BASH_SOURCE")")
. "$HERE/_env"
. "$HERE/_trap"

m 'stopping controllers...'

"$HERE/stop-service" tko-meta-scheduler
"$HERE/stop-service" tko-preparer
"$HERE/stop-service" tko-api

if [ "$1" == -c ]; then
	m 'deleting clusters...'
    kind delete cluster --name=edge1 || true
    kind delete cluster --name=edge2 || true
fi

m 'building...'

"$HERE/build"

m 'starting controllers...'

"$HERE/start-service" tko-api
"$HERE/start-service" tko-preparer
"$HERE/start-service" tko-meta-scheduler

set +e
while true; do
	m 'waiting for tko-api...'
	if tko template list --quiet; then
		break
	fi
	sleep 1
done
set -e

"$HERE/test-scenario" local

m 'templates:'

tko template list

m 'sites:'

tko site list

m 'plugins:'

tko plugin list

m 'deployments:'

tko deployment list
