# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from tko import tko_pb2 as tko_dot_tko__pb2

GRPC_GENERATED_VERSION = '1.66.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in tko/tko_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DataStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.about = channel.unary_unary(
                '/tko.Data/about',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=tko_dot_tko__pb2.AboutResponse.FromString,
                _registered_method=True)
        self.registerTemplate = channel.unary_unary(
                '/tko.Data/registerTemplate',
                request_serializer=tko_dot_tko__pb2.Template.SerializeToString,
                response_deserializer=tko_dot_tko__pb2.RegisterResponse.FromString,
                _registered_method=True)
        self.deleteTemplate = channel.unary_unary(
                '/tko.Data/deleteTemplate',
                request_serializer=tko_dot_tko__pb2.TemplateID.SerializeToString,
                response_deserializer=tko_dot_tko__pb2.DeleteResponse.FromString,
                _registered_method=True)
        self.getTemplate = channel.unary_unary(
                '/tko.Data/getTemplate',
                request_serializer=tko_dot_tko__pb2.GetTemplate.SerializeToString,
                response_deserializer=tko_dot_tko__pb2.Template.FromString,
                _registered_method=True)
        self.listTemplates = channel.unary_stream(
                '/tko.Data/listTemplates',
                request_serializer=tko_dot_tko__pb2.ListTemplates.SerializeToString,
                response_deserializer=tko_dot_tko__pb2.ListedTemplate.FromString,
                _registered_method=True)
        self.purgeTemplates = channel.unary_unary(
                '/tko.Data/purgeTemplates',
                request_serializer=tko_dot_tko__pb2.SelectTemplates.SerializeToString,
                response_deserializer=tko_dot_tko__pb2.DeleteResponse.FromString,
                _registered_method=True)
        self.registerSite = channel.unary_unary(
                '/tko.Data/registerSite',
                request_serializer=tko_dot_tko__pb2.Site.SerializeToString,
                response_deserializer=tko_dot_tko__pb2.RegisterResponse.FromString,
                _registered_method=True)
        self.deleteSite = channel.unary_unary(
                '/tko.Data/deleteSite',
                request_serializer=tko_dot_tko__pb2.SiteID.SerializeToString,
                response_deserializer=tko_dot_tko__pb2.DeleteResponse.FromString,
                _registered_method=True)
        self.getSite = channel.unary_unary(
                '/tko.Data/getSite',
                request_serializer=tko_dot_tko__pb2.GetSite.SerializeToString,
                response_deserializer=tko_dot_tko__pb2.Site.FromString,
                _registered_method=True)
        self.listSites = channel.unary_stream(
                '/tko.Data/listSites',
                request_serializer=tko_dot_tko__pb2.ListSites.SerializeToString,
                response_deserializer=tko_dot_tko__pb2.ListedSite.FromString,
                _registered_method=True)
        self.purgeSites = channel.unary_unary(
                '/tko.Data/purgeSites',
                request_serializer=tko_dot_tko__pb2.SelectSites.SerializeToString,
                response_deserializer=tko_dot_tko__pb2.DeleteResponse.FromString,
                _registered_method=True)
        self.createDeployment = channel.unary_unary(
                '/tko.Data/createDeployment',
                request_serializer=tko_dot_tko__pb2.CreateDeployment.SerializeToString,
                response_deserializer=tko_dot_tko__pb2.CreateDeploymentResponse.FromString,
                _registered_method=True)
        self.deleteDeployment = channel.unary_unary(
                '/tko.Data/deleteDeployment',
                request_serializer=tko_dot_tko__pb2.DeploymentID.SerializeToString,
                response_deserializer=tko_dot_tko__pb2.DeleteResponse.FromString,
                _registered_method=True)
        self.getDeployment = channel.unary_unary(
                '/tko.Data/getDeployment',
                request_serializer=tko_dot_tko__pb2.GetDeployment.SerializeToString,
                response_deserializer=tko_dot_tko__pb2.Deployment.FromString,
                _registered_method=True)
        self.listDeployments = channel.unary_stream(
                '/tko.Data/listDeployments',
                request_serializer=tko_dot_tko__pb2.ListDeployments.SerializeToString,
                response_deserializer=tko_dot_tko__pb2.ListedDeployment.FromString,
                _registered_method=True)
        self.purgeDeployments = channel.unary_unary(
                '/tko.Data/purgeDeployments',
                request_serializer=tko_dot_tko__pb2.SelectDeployments.SerializeToString,
                response_deserializer=tko_dot_tko__pb2.DeleteResponse.FromString,
                _registered_method=True)
        self.startDeploymentModification = channel.unary_unary(
                '/tko.Data/startDeploymentModification',
                request_serializer=tko_dot_tko__pb2.StartDeploymentModification.SerializeToString,
                response_deserializer=tko_dot_tko__pb2.StartDeploymentModificationResponse.FromString,
                _registered_method=True)
        self.endDeploymentModification = channel.unary_unary(
                '/tko.Data/endDeploymentModification',
                request_serializer=tko_dot_tko__pb2.EndDeploymentModification.SerializeToString,
                response_deserializer=tko_dot_tko__pb2.EndDeploymentModificationResponse.FromString,
                _registered_method=True)
        self.cancelDeploymentModification = channel.unary_unary(
                '/tko.Data/cancelDeploymentModification',
                request_serializer=tko_dot_tko__pb2.CancelDeploymentModification.SerializeToString,
                response_deserializer=tko_dot_tko__pb2.CancelDeploymentModificationResponse.FromString,
                _registered_method=True)
        self.registerPlugin = channel.unary_unary(
                '/tko.Data/registerPlugin',
                request_serializer=tko_dot_tko__pb2.Plugin.SerializeToString,
                response_deserializer=tko_dot_tko__pb2.RegisterResponse.FromString,
                _registered_method=True)
        self.deletePlugin = channel.unary_unary(
                '/tko.Data/deletePlugin',
                request_serializer=tko_dot_tko__pb2.PluginID.SerializeToString,
                response_deserializer=tko_dot_tko__pb2.DeleteResponse.FromString,
                _registered_method=True)
        self.getPlugin = channel.unary_unary(
                '/tko.Data/getPlugin',
                request_serializer=tko_dot_tko__pb2.PluginID.SerializeToString,
                response_deserializer=tko_dot_tko__pb2.Plugin.FromString,
                _registered_method=True)
        self.listPlugins = channel.unary_stream(
                '/tko.Data/listPlugins',
                request_serializer=tko_dot_tko__pb2.ListPlugins.SerializeToString,
                response_deserializer=tko_dot_tko__pb2.Plugin.FromString,
                _registered_method=True)
        self.purgePlugins = channel.unary_unary(
                '/tko.Data/purgePlugins',
                request_serializer=tko_dot_tko__pb2.SelectPlugins.SerializeToString,
                response_deserializer=tko_dot_tko__pb2.DeleteResponse.FromString,
                _registered_method=True)


class DataServicer(object):
    """Missing associated documentation comment in .proto file."""

    def about(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def registerTemplate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def deleteTemplate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getTemplate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def listTemplates(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def purgeTemplates(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def registerSite(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def deleteSite(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getSite(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def listSites(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def purgeSites(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def createDeployment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def deleteDeployment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getDeployment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def listDeployments(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def purgeDeployments(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def startDeploymentModification(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def endDeploymentModification(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def cancelDeploymentModification(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def registerPlugin(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def deletePlugin(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getPlugin(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def listPlugins(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def purgePlugins(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DataServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'about': grpc.unary_unary_rpc_method_handler(
                    servicer.about,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=tko_dot_tko__pb2.AboutResponse.SerializeToString,
            ),
            'registerTemplate': grpc.unary_unary_rpc_method_handler(
                    servicer.registerTemplate,
                    request_deserializer=tko_dot_tko__pb2.Template.FromString,
                    response_serializer=tko_dot_tko__pb2.RegisterResponse.SerializeToString,
            ),
            'deleteTemplate': grpc.unary_unary_rpc_method_handler(
                    servicer.deleteTemplate,
                    request_deserializer=tko_dot_tko__pb2.TemplateID.FromString,
                    response_serializer=tko_dot_tko__pb2.DeleteResponse.SerializeToString,
            ),
            'getTemplate': grpc.unary_unary_rpc_method_handler(
                    servicer.getTemplate,
                    request_deserializer=tko_dot_tko__pb2.GetTemplate.FromString,
                    response_serializer=tko_dot_tko__pb2.Template.SerializeToString,
            ),
            'listTemplates': grpc.unary_stream_rpc_method_handler(
                    servicer.listTemplates,
                    request_deserializer=tko_dot_tko__pb2.ListTemplates.FromString,
                    response_serializer=tko_dot_tko__pb2.ListedTemplate.SerializeToString,
            ),
            'purgeTemplates': grpc.unary_unary_rpc_method_handler(
                    servicer.purgeTemplates,
                    request_deserializer=tko_dot_tko__pb2.SelectTemplates.FromString,
                    response_serializer=tko_dot_tko__pb2.DeleteResponse.SerializeToString,
            ),
            'registerSite': grpc.unary_unary_rpc_method_handler(
                    servicer.registerSite,
                    request_deserializer=tko_dot_tko__pb2.Site.FromString,
                    response_serializer=tko_dot_tko__pb2.RegisterResponse.SerializeToString,
            ),
            'deleteSite': grpc.unary_unary_rpc_method_handler(
                    servicer.deleteSite,
                    request_deserializer=tko_dot_tko__pb2.SiteID.FromString,
                    response_serializer=tko_dot_tko__pb2.DeleteResponse.SerializeToString,
            ),
            'getSite': grpc.unary_unary_rpc_method_handler(
                    servicer.getSite,
                    request_deserializer=tko_dot_tko__pb2.GetSite.FromString,
                    response_serializer=tko_dot_tko__pb2.Site.SerializeToString,
            ),
            'listSites': grpc.unary_stream_rpc_method_handler(
                    servicer.listSites,
                    request_deserializer=tko_dot_tko__pb2.ListSites.FromString,
                    response_serializer=tko_dot_tko__pb2.ListedSite.SerializeToString,
            ),
            'purgeSites': grpc.unary_unary_rpc_method_handler(
                    servicer.purgeSites,
                    request_deserializer=tko_dot_tko__pb2.SelectSites.FromString,
                    response_serializer=tko_dot_tko__pb2.DeleteResponse.SerializeToString,
            ),
            'createDeployment': grpc.unary_unary_rpc_method_handler(
                    servicer.createDeployment,
                    request_deserializer=tko_dot_tko__pb2.CreateDeployment.FromString,
                    response_serializer=tko_dot_tko__pb2.CreateDeploymentResponse.SerializeToString,
            ),
            'deleteDeployment': grpc.unary_unary_rpc_method_handler(
                    servicer.deleteDeployment,
                    request_deserializer=tko_dot_tko__pb2.DeploymentID.FromString,
                    response_serializer=tko_dot_tko__pb2.DeleteResponse.SerializeToString,
            ),
            'getDeployment': grpc.unary_unary_rpc_method_handler(
                    servicer.getDeployment,
                    request_deserializer=tko_dot_tko__pb2.GetDeployment.FromString,
                    response_serializer=tko_dot_tko__pb2.Deployment.SerializeToString,
            ),
            'listDeployments': grpc.unary_stream_rpc_method_handler(
                    servicer.listDeployments,
                    request_deserializer=tko_dot_tko__pb2.ListDeployments.FromString,
                    response_serializer=tko_dot_tko__pb2.ListedDeployment.SerializeToString,
            ),
            'purgeDeployments': grpc.unary_unary_rpc_method_handler(
                    servicer.purgeDeployments,
                    request_deserializer=tko_dot_tko__pb2.SelectDeployments.FromString,
                    response_serializer=tko_dot_tko__pb2.DeleteResponse.SerializeToString,
            ),
            'startDeploymentModification': grpc.unary_unary_rpc_method_handler(
                    servicer.startDeploymentModification,
                    request_deserializer=tko_dot_tko__pb2.StartDeploymentModification.FromString,
                    response_serializer=tko_dot_tko__pb2.StartDeploymentModificationResponse.SerializeToString,
            ),
            'endDeploymentModification': grpc.unary_unary_rpc_method_handler(
                    servicer.endDeploymentModification,
                    request_deserializer=tko_dot_tko__pb2.EndDeploymentModification.FromString,
                    response_serializer=tko_dot_tko__pb2.EndDeploymentModificationResponse.SerializeToString,
            ),
            'cancelDeploymentModification': grpc.unary_unary_rpc_method_handler(
                    servicer.cancelDeploymentModification,
                    request_deserializer=tko_dot_tko__pb2.CancelDeploymentModification.FromString,
                    response_serializer=tko_dot_tko__pb2.CancelDeploymentModificationResponse.SerializeToString,
            ),
            'registerPlugin': grpc.unary_unary_rpc_method_handler(
                    servicer.registerPlugin,
                    request_deserializer=tko_dot_tko__pb2.Plugin.FromString,
                    response_serializer=tko_dot_tko__pb2.RegisterResponse.SerializeToString,
            ),
            'deletePlugin': grpc.unary_unary_rpc_method_handler(
                    servicer.deletePlugin,
                    request_deserializer=tko_dot_tko__pb2.PluginID.FromString,
                    response_serializer=tko_dot_tko__pb2.DeleteResponse.SerializeToString,
            ),
            'getPlugin': grpc.unary_unary_rpc_method_handler(
                    servicer.getPlugin,
                    request_deserializer=tko_dot_tko__pb2.PluginID.FromString,
                    response_serializer=tko_dot_tko__pb2.Plugin.SerializeToString,
            ),
            'listPlugins': grpc.unary_stream_rpc_method_handler(
                    servicer.listPlugins,
                    request_deserializer=tko_dot_tko__pb2.ListPlugins.FromString,
                    response_serializer=tko_dot_tko__pb2.Plugin.SerializeToString,
            ),
            'purgePlugins': grpc.unary_unary_rpc_method_handler(
                    servicer.purgePlugins,
                    request_deserializer=tko_dot_tko__pb2.SelectPlugins.FromString,
                    response_serializer=tko_dot_tko__pb2.DeleteResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'tko.Data', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('tko.Data', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Data(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def about(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tko.Data/about',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            tko_dot_tko__pb2.AboutResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def registerTemplate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tko.Data/registerTemplate',
            tko_dot_tko__pb2.Template.SerializeToString,
            tko_dot_tko__pb2.RegisterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def deleteTemplate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tko.Data/deleteTemplate',
            tko_dot_tko__pb2.TemplateID.SerializeToString,
            tko_dot_tko__pb2.DeleteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def getTemplate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tko.Data/getTemplate',
            tko_dot_tko__pb2.GetTemplate.SerializeToString,
            tko_dot_tko__pb2.Template.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def listTemplates(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/tko.Data/listTemplates',
            tko_dot_tko__pb2.ListTemplates.SerializeToString,
            tko_dot_tko__pb2.ListedTemplate.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def purgeTemplates(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tko.Data/purgeTemplates',
            tko_dot_tko__pb2.SelectTemplates.SerializeToString,
            tko_dot_tko__pb2.DeleteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def registerSite(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tko.Data/registerSite',
            tko_dot_tko__pb2.Site.SerializeToString,
            tko_dot_tko__pb2.RegisterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def deleteSite(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tko.Data/deleteSite',
            tko_dot_tko__pb2.SiteID.SerializeToString,
            tko_dot_tko__pb2.DeleteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def getSite(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tko.Data/getSite',
            tko_dot_tko__pb2.GetSite.SerializeToString,
            tko_dot_tko__pb2.Site.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def listSites(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/tko.Data/listSites',
            tko_dot_tko__pb2.ListSites.SerializeToString,
            tko_dot_tko__pb2.ListedSite.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def purgeSites(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tko.Data/purgeSites',
            tko_dot_tko__pb2.SelectSites.SerializeToString,
            tko_dot_tko__pb2.DeleteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def createDeployment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tko.Data/createDeployment',
            tko_dot_tko__pb2.CreateDeployment.SerializeToString,
            tko_dot_tko__pb2.CreateDeploymentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def deleteDeployment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tko.Data/deleteDeployment',
            tko_dot_tko__pb2.DeploymentID.SerializeToString,
            tko_dot_tko__pb2.DeleteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def getDeployment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tko.Data/getDeployment',
            tko_dot_tko__pb2.GetDeployment.SerializeToString,
            tko_dot_tko__pb2.Deployment.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def listDeployments(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/tko.Data/listDeployments',
            tko_dot_tko__pb2.ListDeployments.SerializeToString,
            tko_dot_tko__pb2.ListedDeployment.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def purgeDeployments(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tko.Data/purgeDeployments',
            tko_dot_tko__pb2.SelectDeployments.SerializeToString,
            tko_dot_tko__pb2.DeleteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def startDeploymentModification(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tko.Data/startDeploymentModification',
            tko_dot_tko__pb2.StartDeploymentModification.SerializeToString,
            tko_dot_tko__pb2.StartDeploymentModificationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def endDeploymentModification(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tko.Data/endDeploymentModification',
            tko_dot_tko__pb2.EndDeploymentModification.SerializeToString,
            tko_dot_tko__pb2.EndDeploymentModificationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def cancelDeploymentModification(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tko.Data/cancelDeploymentModification',
            tko_dot_tko__pb2.CancelDeploymentModification.SerializeToString,
            tko_dot_tko__pb2.CancelDeploymentModificationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def registerPlugin(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tko.Data/registerPlugin',
            tko_dot_tko__pb2.Plugin.SerializeToString,
            tko_dot_tko__pb2.RegisterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def deletePlugin(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tko.Data/deletePlugin',
            tko_dot_tko__pb2.PluginID.SerializeToString,
            tko_dot_tko__pb2.DeleteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def getPlugin(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tko.Data/getPlugin',
            tko_dot_tko__pb2.PluginID.SerializeToString,
            tko_dot_tko__pb2.Plugin.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def listPlugins(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/tko.Data/listPlugins',
            tko_dot_tko__pb2.ListPlugins.SerializeToString,
            tko_dot_tko__pb2.Plugin.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def purgePlugins(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tko.Data/purgePlugins',
            tko_dot_tko__pb2.SelectPlugins.SerializeToString,
            tko_dot_tko__pb2.DeleteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
