// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// DeploymentListerExpansion allows custom methods to be added to
// DeploymentLister.
type DeploymentListerExpansion interface{}

// DeploymentNamespaceListerExpansion allows custom methods to be added to
// DeploymentNamespaceLister.
type DeploymentNamespaceListerExpansion interface{}

// PluginListerExpansion allows custom methods to be added to
// PluginLister.
type PluginListerExpansion interface{}

// PluginNamespaceListerExpansion allows custom methods to be added to
// PluginNamespaceLister.
type PluginNamespaceListerExpansion interface{}

// SiteListerExpansion allows custom methods to be added to
// SiteLister.
type SiteListerExpansion interface{}

// TemplateListerExpansion allows custom methods to be added to
// TemplateLister.
type TemplateListerExpansion interface{}
