// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/nephio-experimental/tko/api/krm/tko.nephio.org/v1alpha1"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/listers"
	"k8s.io/client-go/tools/cache"
)

// TemplateLister helps list Templates.
// All objects returned here must be treated as read-only.
type TemplateLister interface {
	// List lists all Templates in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.Template, err error)
	// Get retrieves the Template from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1alpha1.Template, error)
	TemplateListerExpansion
}

// templateLister implements the TemplateLister interface.
type templateLister struct {
	listers.ResourceIndexer[*v1alpha1.Template]
}

// NewTemplateLister returns a new TemplateLister.
func NewTemplateLister(indexer cache.Indexer) TemplateLister {
	return &templateLister{listers.New[*v1alpha1.Template](indexer, v1alpha1.Resource("template"))}
}
